name: First github action

on: 
  push: 
     branch:
       - GitHub-action-demo-2026


jobs:
  demo-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install nginx
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx
          sudo systemctl status nginx || true

      - name: print current date
        run: date

      - name: print message
        run: echo "Hello! github action working file !!!"
